export default [
    { firstName: "Nola",
        lastName: "Corgi",
        username : "corgi",
        handle: "@corgi",
        password: "12345",
        email: "corgi@gmail.com",
        role: "WRITER",
        photo: "../images/cola.jpg",
        id: "101",
        location: "Boston, MA",
        dateOfBirth: "09/18/2018",
        dateJoined: "3/2023",
        followingCount: 100,
        followersCount: 1000000},
    { firstName: "cookie",
        lastName: "dog",
        username : "cookiethedog",
        handle: "@cookiethedog",
        password: "123456",
        email: "cookiedog@gmail.com",
        role: "WRITER",
        id: "123",
        location: "Sydney, AU",
        dateOfBirth: "01/10/2018",
        dateJoined: "06/2017",
        followingCount: 781,
        followersCount: 300000,
    },
    { firstName: "max",
        lastName: "manatee",
        username : "maxthemanatee",
        handle: "maxthemanatee",
        email: "maxmanataee@gmail.com",
        password: "98765",
        role: "SUBSCRIBER",
        id: "567",
        location: "Los Angeles, CA",
        dateOfBirth: "09/1981",
        dateJoined: "09/2016",
        followingCount: 100,
        followersCount: 20000},
    {   firstName: "Cola",
        lastName: "the Cat",
        username: "colathecat",
        handle: "colathecat",
        email: "colacat@gmail.com",
        password: "567890",
        role: "WRITER",
        _id: "107",
        location: "NYC",
        dateOfBirth: "08/21/1970",
        dateJoined: "06/2021",
        followingCount: 256,
        followersCount: 50108
    },
    {firstName: "Mike",
    lastName: "the Manatee",
    username: "a",
    handle: "mikethemanatee",
    email: "mikethemanatee@gmail.com",
    password: "a",
    role: "WRITER",
    photo:  "../images/cola.jpg",
    id: "789",
    location: "NYC",
    dateOfBirth: "08/21/1970",
    dateJoined: "06/2021",
    followingCount: 256,
    followersCount: 50108}
]
